### ISSUE TITLE
Adding cpas to my AOF3 server results in a crash-loop on startup

### ISSUE THREAD

**Issue by ImJustMatt** [badasintended/cpas#1]
I understand this is more of an edge case since cpas is being tested against 150+ other mods, but it would be nice if this could be added.

Here is a copy of the log from when the server crashed
https://gist.github.com/ImJustMatt/78d37d9635fe8c2e195da0f94c357b8f

I can also add a log from a successful launch (without cpas installed) if that helps.

**Comment by deirn** [comment]
🤦‍♂️ the client annotation is switched between common and client main class... I'm surprised it takes this long for someone to report. Sorry for the inconvenience (pretty ironic isn't it).
