### ISSUE TITLE
incompatibility with curios

### ISSUE THREAD

**Issue by SylisMC** [badasintended/cpas#2]
Curios overlay and CPAS slots overlay each other and are in the way

**Comment by SylisMC** [comment]
I've noticed that there is an option in the config to remove them but moving the location would be helpful

**Comment by deirn** [comment]
you can move them, disable the "Auto" mode and you can drag the panel around

**Comment by SylisMC** [comment]
okay, How do I do that? the mod isn't compatible with mod menu and there is no "auto" setting in the config
`{
  "showHelp": false,
  "entries": {
    "com.github.minnecraeft.packed.client.GenericScreen": true,
    "net.minecraft.class_479": true
  }
}`

**Comment by deirn** [comment]
press Ctrl-J when in inventory, or disable `showHelp` to show the toast again. the config entry then will something like `"pkg.screenclass": [x, y]`, wich is the panel top left corner coord from the center of the screen

**Comment by SylisMC** [comment]
That's actually really helpful. I now realize it says that right on the mod page, I didn't notice it before, thanks for the help, and sorry to waste your time
