### ISSUE TITLE
[feature request] use texture pack to decorate cpas inventory

### ISSUE THREAD

**Issue by MeeniMc** [badasintended/cpas#6]
I use Vanilla Tweaks 'dark UI', which sets the color of the various inventory to a darker gray. However, the CPAS inventory remains 'light' colored.

It would be great if the CPAS inventory would create it's texture from elements of the texture pack.

If you want an example of that idea at work, in the mod tweakeroo, the function 'preview shulker' feature does create it's interface that way.

**Comment by Jedicatt** [comment]
I have created a dark theme hopefully it fulfills your needs 
[CPAS Dark Theme.zip](https://github.com/badasintended/cpas/files/6759367/CPAS.Dark.Theme.zip)
