### ISSUE TITLE
cpas requires {fabric @ [>=0.30.0]} -- Latest is Fabric 0.11.6

### ISSUE THREAD

**Issue by SeasonalFerret** [badasintended/cpas#8]
![image](https://user-images.githubusercontent.com/17802843/132983851-b50eab4a-1fea-4b89-be2a-51e2aa7f914e.png)
![image](https://user-images.githubusercontent.com/17802843/132983861-3651cc47-266a-46bd-a795-5176527e5faf.png)

I'd like to assume that the mod is incorrectly checking for `fabric`, when it should be checking for `fabricapi`. 
![image](https://user-images.githubusercontent.com/17802843/132983893-e7e74959-18f9-4db2-b3b5-394e1785234a.png)

**Comment by SeasonalFerret** [comment]
I've encountered this same issue with another mod, and have deemed this to be a personal issue. 
Feel free to delete this issue if no others have the problem.

**Comment by deirn** [comment]
Fabric API's id is `fabric`
https://github.com/FabricMC/fabric/blob/46582230fb580d4c1f71e4b0737df27417ec9cb1/src/main/resources/fabric.mod.json#L1-L5

**Comment by SeasonalFerret** [comment]
> Fabric API's id is `fabric`

Learn something new every day, huh? 

Again, my apologies for this trash issue. It appears that another mod caused this issue. 
[For anyone curious](https://github.com/HughBone/fabrilous-updater/issues/8), which I'd imagine no one since I'm probably the only one who had this issue.
